import type { Journalist } from '../types'

export const ARGENTINA_JOURNALISTS: Journalist[] = [
  {
    id: 'juan-pablo-varsky',
    name: 'Juan Pablo Varsky',
    country: 'argentina',
    mediaOutlets: ['espn_argentina'],
    primaryLeagues: ['Liga Profesional Argentina'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Liga Profesional Argentina', 'Libertadores'],
    roles: ['tactical_analyst', 'analyst'],
    specialties: ['tactics', 'national_team', 'domestic_league'],
    eventTypes: ['TACTICAL_CHANGE', 'MATCH_RESULT', 'DERBY', 'LIBERTADORES_EVENT', 'CUP_FINAL'],
    tone: 'analytical',
    controversyLevel: 0.2,
    tacticalDepth: 0.7,
    transferReliability: 'OPINION',
    internationalReach: 0.2,
    domesticReach: 0.7,
    clubSpecificity: 0,
    defaultWeight: 0.45,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS', 'TRANSFER_UPDATE'],
  },
  {
    id: 'mariano-closs',
    name: 'Mariano Closs',
    country: 'argentina',
    mediaOutlets: ['tyc_sports'],
    primaryLeagues: ['Liga Profesional Argentina'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Liga Profesional Argentina', 'Libertadores'],
    roles: ['presenter', 'commentator'],
    specialties: ['domestic_league'],
    eventTypes: ['MATCH_RESULT', 'DERBY', 'RIVALRY_MATCH', 'CUP_FINAL', 'LIBERTADORES_EVENT', 'WINNING_STREAK', 'HISTORIC_RESULT'],
    tone: 'measured',
    controversyLevel: 0.2,
    tacticalDepth: 0.25,
    transferReliability: 'OPINION',
    internationalReach: 0.2,
    domesticReach: 0.8,
    clubSpecificity: 0,
    defaultWeight: 0.45,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS'],
  },
  {
    id: 'sebastian-vignolo',
    name: 'Sebastián Vignolo',
    country: 'argentina',
    mediaOutlets: ['espn_argentina'],
    primaryLeagues: ['Liga Profesional Argentina'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Liga Profesional Argentina', 'Libertadores'],
    roles: ['presenter', 'commentator'],
    specialties: ['domestic_league', 'coaching'],
    eventTypes: ['MATCH_RESULT', 'MANAGER_PRESSURE', 'MANAGER_PRAISE', 'DERBY', 'CUP_FINAL', 'LIBERTADORES_EVENT'],
    tone: 'measured',
    controversyLevel: 0.3,
    tacticalDepth: 0.3,
    transferReliability: 'OPINION',
    internationalReach: 0.15,
    domesticReach: 0.75,
    clubSpecificity: 0,
    defaultWeight: 0.4,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS'],
  },
  {
    id: 'flavio-azzaro',
    name: 'Flavio Azzaro',
    country: 'argentina',
    mediaOutlets: ['tyc_sports'],
    primaryLeagues: ['Liga Profesional Argentina'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Liga Profesional Argentina'],
    roles: ['columnist'],
    specialties: ['club_management', 'coaching'],
    eventTypes: ['MANAGER_PRESSURE', 'BOARD_DECISION', 'CLUB_CRISIS', 'LOSING_STREAK', 'CONTROVERSY'],
    tone: 'provocative',
    controversyLevel: 0.9,
    tacticalDepth: 0.15,
    transferReliability: 'OPINION',
    internationalReach: 0.1,
    domesticReach: 0.6,
    clubSpecificity: 0,
    // "Utilizar com moderação" no doc — peso base mais baixo, deixa a penalidade de overuse fazer o resto.
    defaultWeight: 0.3,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS', 'TACTICAL_ANALYSIS'],
  },
  {
    id: 'gustavo-lopez',
    name: 'Gustavo López',
    country: 'argentina',
    mediaOutlets: ['espn_argentina'],
    primaryLeagues: ['Liga Profesional Argentina'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Liga Profesional Argentina'],
    roles: ['commentator', 'reporter'],
    specialties: ['domestic_league'],
    eventTypes: ['MATCH_RESULT', 'DERBY', 'TRANSFER_COMPLETED'],
    tone: 'measured',
    controversyLevel: 0.3,
    tacticalDepth: 0.25,
    transferReliability: 'OPINION',
    internationalReach: 0.1,
    domesticReach: 0.55,
    clubSpecificity: 0,
    defaultWeight: 0.3,
    active: true,
    excludedRoleInStory: ['TACTICAL_ANALYSIS'],
  },
]
