import type { Journalist } from '../types'

export const BRAZIL_JOURNALISTS: Journalist[] = [
  {
    id: 'paulo-vinicius-coelho',
    name: 'Paulo Vinícius Coelho',
    country: 'brazil',
    mediaOutlets: ['uol', 'espn_brasil'],
    primaryLeagues: ['Brasileirão', 'Copa do Brasil', 'Libertadores'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Brasileirão', 'Copa do Brasil', 'Libertadores', 'Copa Sul-Americana'],
    roles: ['columnist', 'analyst'],
    specialties: ['history', 'domestic_league', 'club_management', 'coaching'],
    eventTypes: [
      'HISTORIC_RESULT', 'RECORD_BROKEN', 'TITLE_RACE', 'RELEGATION_BATTLE', 'MANAGER_PRESSURE', 'MANAGER_PRAISE',
      'CLUB_CRISIS', 'SEASON_START', 'GENERIC',
    ],
    tone: 'analytical',
    controversyLevel: 0.2,
    tacticalDepth: 0.4,
    transferReliability: 'OPINION',
    internationalReach: 0.2,
    domesticReach: 0.85,
    clubSpecificity: 0,
    defaultWeight: 0.6,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS', 'TRANSFER_UPDATE'],
  },
  {
    id: 'mauro-cezar-pereira',
    name: 'Mauro Cezar Pereira',
    country: 'brazil',
    mediaOutlets: ['uol'],
    primaryLeagues: ['Brasileirão', 'Copa do Brasil', 'Libertadores'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Brasileirão', 'Copa do Brasil', 'Libertadores'],
    roles: ['columnist'],
    specialties: ['club_management', 'coaching'],
    eventTypes: [
      'MANAGER_PRESSURE', 'BOARD_DECISION', 'FINANCIAL_DECISION', 'CLUB_CRISIS', 'LOSING_STREAK', 'RELEGATION_BATTLE',
      'CONTROVERSY', 'LINEUP_CHANGE',
    ],
    tone: 'critical',
    controversyLevel: 0.85,
    tacticalDepth: 0.2,
    transferReliability: 'OPINION',
    internationalReach: 0.1,
    domesticReach: 0.8,
    clubSpecificity: 0,
    defaultWeight: 0.55,
    active: true,
    excludedRoleInStory: ['TACTICAL_ANALYSIS', 'BREAKING_NEWS'],
  },
  {
    id: 'andre-rizek',
    name: 'André Rizek',
    country: 'brazil',
    mediaOutlets: ['globo', 'sportv'],
    primaryLeagues: ['Brasileirão', 'Copa do Brasil', 'Libertadores'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Brasileirão', 'Copa do Brasil', 'Libertadores'],
    roles: ['presenter', 'commentator'],
    specialties: ['domestic_league', 'players', 'coaching'],
    eventTypes: [
      'MATCH_RESULT', 'DERBY', 'RIVALRY_MATCH', 'CUP_FINAL', 'CUP_ELIMINATION', 'WINNING_STREAK', 'LOSING_STREAK',
      'MANAGER_PRESSURE', 'MANAGER_PRAISE', 'TITLE_RACE',
    ],
    tone: 'measured',
    controversyLevel: 0.3,
    tacticalDepth: 0.3,
    transferReliability: 'OPINION',
    internationalReach: 0.1,
    domesticReach: 0.75,
    clubSpecificity: 0,
    defaultWeight: 0.45,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS'],
  },
  {
    id: 'leonardo-bertozzi',
    name: 'Leonardo Bertozzi',
    country: 'brazil',
    mediaOutlets: ['espn_brasil'],
    primaryLeagues: ['Brasileirão'],
    secondaryLeagues: ['Premier League', 'Serie A', 'La Liga', 'Champions League'],
    clubAffinities: [],
    competitions: ['Champions League', 'Libertadores', 'Brasileirão'],
    roles: ['analyst', 'commentator'],
    specialties: ['international_football', 'history', 'domestic_league'],
    eventTypes: ['CHAMPIONS_LEAGUE_EVENT', 'LIBERTADORES_EVENT', 'HISTORIC_RESULT', 'MATCH_RESULT', 'CUP_FINAL'],
    tone: 'analytical',
    controversyLevel: 0.2,
    tacticalDepth: 0.5,
    transferReliability: 'OPINION',
    internationalReach: 0.4,
    domesticReach: 0.5,
    clubSpecificity: 0,
    defaultWeight: 0.4,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS'],
  },
  {
    id: 'rafael-oliveira',
    name: 'Rafael Oliveira',
    country: 'brazil',
    mediaOutlets: ['ge', 'sportv'],
    primaryLeagues: ['Brasileirão', 'Copa do Brasil', 'Libertadores'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Brasileirão', 'Copa do Brasil', 'Libertadores'],
    roles: ['tactical_analyst', 'analyst'],
    specialties: ['tactics', 'players', 'youth'],
    eventTypes: [
      'TACTICAL_CHANGE', 'LINEUP_CHANGE', 'PLAYER_FORM', 'PLAYER_BREAKOUT', 'MATCH_RESULT', 'DERBY', 'CUP_FINAL',
      'CUP_ELIMINATION',
    ],
    tone: 'technical',
    controversyLevel: 0.15,
    tacticalDepth: 0.9,
    transferReliability: 'OPINION',
    internationalReach: 0.1,
    domesticReach: 0.6,
    clubSpecificity: 0,
    defaultWeight: 0.5,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS', 'TRANSFER_UPDATE'],
  },
]
