import type { Journalist } from '../types'

export const ENGLAND_JOURNALISTS: Journalist[] = [
  {
    id: 'david-ornstein',
    name: 'David Ornstein',
    country: 'england',
    mediaOutlets: ['the_athletic'],
    primaryLeagues: ['Premier League', 'Championship'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Premier League', 'FA Cup', 'Champions League'],
    roles: ['transfer_reporter', 'reporter'],
    specialties: ['transfers', 'contracts', 'club_management'],
    eventTypes: [
      'TRANSFER_RUMOR', 'TRANSFER_NEGOTIATION', 'TRANSFER_COMPLETED', 'PLAYER_SALE', 'PLAYER_LOAN',
      'CONTRACT_RENEWAL', 'CONTRACT_BREAKDOWN', 'BOARD_DECISION',
    ],
    tone: 'factual',
    controversyLevel: 0.1,
    tacticalDepth: 0.1,
    transferReliability: 'TIER_1',
    internationalReach: 0.6,
    domesticReach: 0.9,
    clubSpecificity: 0,
    defaultWeight: 0.7,
    active: true,
    excludedRoleInStory: ['POST_MATCH_REACTION', 'TACTICAL_ANALYSIS', 'CRITICISM'],
  },
  {
    id: 'gary-neville',
    name: 'Gary Neville',
    country: 'england',
    mediaOutlets: ['sky_sports'],
    primaryLeagues: ['Premier League'],
    secondaryLeagues: ['Champions League'],
    clubAffinities: [{ clubName: 'Manchester United', level: 'HIGH' }],
    competitions: ['Premier League', 'Champions League', 'FA Cup'],
    roles: ['former_player', 'commentator'],
    specialties: ['club_management', 'coaching', 'players'],
    eventTypes: [
      'MATCH_RESULT', 'MANAGER_PRESSURE', 'MANAGER_PRAISE', 'DERBY', 'RIVALRY_MATCH', 'CUP_FINAL', 'CUP_ELIMINATION',
      'CHAMPIONS_LEAGUE_EVENT', 'CLUB_CRISIS', 'BOARD_DECISION', 'WINNING_STREAK', 'LOSING_STREAK',
    ],
    tone: 'critical',
    controversyLevel: 0.7,
    tacticalDepth: 0.5,
    transferReliability: 'OPINION',
    internationalReach: 0.8,
    domesticReach: 0.9,
    clubSpecificity: 0.6,
    defaultWeight: 0.65,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS', 'TRANSFER_UPDATE'],
  },
  {
    id: 'jamie-carragher',
    name: 'Jamie Carragher',
    country: 'england',
    mediaOutlets: ['sky_sports'],
    primaryLeagues: ['Premier League'],
    secondaryLeagues: ['Champions League'],
    clubAffinities: [{ clubName: 'Liverpool', level: 'HIGH' }],
    competitions: ['Premier League', 'Champions League'],
    roles: ['former_player', 'tactical_analyst'],
    specialties: ['tactics', 'players'],
    eventTypes: [
      'MATCH_RESULT', 'TACTICAL_CHANGE', 'DERBY', 'RIVALRY_MATCH', 'CUP_FINAL', 'CHAMPIONS_LEAGUE_EVENT',
      'MANAGER_PRESSURE', 'WINNING_STREAK', 'LOSING_STREAK',
    ],
    tone: 'technical',
    controversyLevel: 0.55,
    tacticalDepth: 0.75,
    transferReliability: 'OPINION',
    internationalReach: 0.75,
    domesticReach: 0.9,
    clubSpecificity: 0.6,
    defaultWeight: 0.6,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS', 'TRANSFER_UPDATE'],
  },
  {
    id: 'henry-winter',
    name: 'Henry Winter',
    country: 'england',
    mediaOutlets: ['the_athletic'],
    primaryLeagues: ['Premier League', 'Championship'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Premier League', 'FA Cup', 'Champions League'],
    roles: ['columnist', 'reporter'],
    specialties: ['history', 'national_team', 'coaching'],
    eventTypes: ['HISTORIC_RESULT', 'RECORD_BROKEN', 'CUP_FINAL', 'MANAGER_PRESSURE', 'MANAGER_PRAISE', 'TITLE_RACE', 'CLUB_CRISIS'],
    tone: 'institutional',
    controversyLevel: 0.25,
    tacticalDepth: 0.3,
    transferReliability: 'OPINION',
    internationalReach: 0.35,
    domesticReach: 0.75,
    clubSpecificity: 0,
    defaultWeight: 0.45,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS'],
  },
  {
    id: 'rory-smith',
    name: 'Rory Smith',
    country: 'england',
    mediaOutlets: ['the_athletic'],
    primaryLeagues: ['Premier League'],
    secondaryLeagues: ['Champions League', 'La Liga', 'Serie A', 'Bundesliga'],
    clubAffinities: [],
    competitions: ['Premier League', 'Champions League'],
    roles: ['columnist'],
    specialties: ['history', 'club_management', 'ownership'],
    eventTypes: ['BOARD_DECISION', 'FINANCIAL_DECISION', 'CLUB_CRISIS', 'HISTORIC_RESULT', 'MANAGER_PRESSURE', 'TACTICAL_CHANGE'],
    tone: 'sophisticated',
    controversyLevel: 0.2,
    tacticalDepth: 0.4,
    transferReliability: 'OPINION',
    internationalReach: 0.5,
    domesticReach: 0.6,
    clubSpecificity: 0,
    defaultWeight: 0.4,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS', 'TRANSFER_UPDATE'],
  },
]
