import type { Journalist } from '../types'

export const FRANCE_JOURNALISTS: Journalist[] = [
  {
    id: 'daniel-riolo',
    name: 'Daniel Riolo',
    country: 'france',
    mediaOutlets: ['rmc_sport'],
    primaryLeagues: ['Ligue 1'],
    secondaryLeagues: [],
    clubAffinities: [{ clubName: 'Paris Saint-Germain', level: 'HIGH' }],
    competitions: ['Ligue 1', 'Champions League'],
    roles: ['columnist'],
    specialties: ['club_management', 'coaching'],
    eventTypes: ['MANAGER_PRESSURE', 'BOARD_DECISION', 'CLUB_CRISIS', 'LOSING_STREAK', 'CONTROVERSY', 'MATCH_RESULT'],
    tone: 'provocative',
    controversyLevel: 0.85,
    tacticalDepth: 0.3,
    transferReliability: 'OPINION',
    internationalReach: 0.15,
    domesticReach: 0.8,
    clubSpecificity: 0.5,
    defaultWeight: 0.5,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS', 'TACTICAL_ANALYSIS'],
  },
  {
    id: 'vincent-duluc',
    name: 'Vincent Duluc',
    country: 'france',
    mediaOutlets: ['lequipe'],
    primaryLeagues: ['Ligue 1'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Ligue 1', 'Champions League'],
    roles: ['columnist', 'reporter'],
    specialties: ['history', 'national_team', 'domestic_league'],
    eventTypes: ['HISTORIC_RESULT', 'MATCH_RESULT', 'TITLE_RACE', 'MANAGER_PRESSURE', 'MANAGER_PRAISE', 'CUP_FINAL'],
    tone: 'institutional',
    controversyLevel: 0.2,
    tacticalDepth: 0.3,
    transferReliability: 'OPINION',
    internationalReach: 0.2,
    domesticReach: 0.7,
    clubSpecificity: 0,
    defaultWeight: 0.45,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS'],
  },
  {
    id: 'loic-tanzi',
    name: 'Loïc Tanzi',
    country: 'france',
    mediaOutlets: ['rmc_sport'],
    primaryLeagues: ['Ligue 1'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Ligue 1'],
    roles: ['transfer_reporter', 'reporter'],
    specialties: ['transfers', 'locker_room'],
    eventTypes: ['TRANSFER_RUMOR', 'TRANSFER_NEGOTIATION', 'TRANSFER_COMPLETED', 'PLAYER_SALE', 'PLAYER_LOAN', 'CONTRACT_RENEWAL'],
    tone: 'factual',
    controversyLevel: 0.15,
    tacticalDepth: 0.1,
    transferReliability: 'TIER_2',
    internationalReach: 0.25,
    domesticReach: 0.65,
    clubSpecificity: 0,
    defaultWeight: 0.4,
    active: true,
    excludedRoleInStory: ['TACTICAL_ANALYSIS', 'POST_MATCH_REACTION'],
  },
  {
    id: 'walid-acherchour',
    name: 'Walid Acherchour',
    country: 'france',
    mediaOutlets: ['rmc_sport'],
    primaryLeagues: ['Ligue 1'],
    secondaryLeagues: ['Premier League', 'La Liga'],
    clubAffinities: [],
    competitions: ['Ligue 1', 'Champions League'],
    roles: ['analyst', 'columnist'],
    specialties: ['players', 'tactics'],
    eventTypes: ['PLAYER_FORM', 'PLAYER_BREAKOUT', 'TACTICAL_CHANGE', 'MATCH_RESULT', 'CONTROVERSY'],
    tone: 'provocative',
    controversyLevel: 0.5,
    tacticalDepth: 0.5,
    transferReliability: 'OPINION',
    internationalReach: 0.15,
    domesticReach: 0.5,
    clubSpecificity: 0,
    defaultWeight: 0.35,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS'],
  },
  {
    id: 'bixente-lizarazu',
    name: 'Bixente Lizarazu',
    country: 'france',
    mediaOutlets: ['tf1', 'rmc_sport'],
    primaryLeagues: ['Ligue 1'],
    secondaryLeagues: ['Bundesliga'],
    clubAffinities: [],
    competitions: ['Ligue 1', 'Champions League'],
    roles: ['former_player', 'commentator'],
    specialties: ['players', 'national_team'],
    eventTypes: ['MATCH_RESULT', 'CUP_FINAL', 'CHAMPIONS_LEAGUE_EVENT', 'PLAYER_FORM', 'DERBY'],
    tone: 'technical',
    controversyLevel: 0.2,
    tacticalDepth: 0.5,
    transferReliability: 'OPINION',
    internationalReach: 0.3,
    domesticReach: 0.55,
    clubSpecificity: 0,
    defaultWeight: 0.35,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS', 'TRANSFER_UPDATE'],
  },
]
