import type { Journalist } from '../types'

export const GERMANY_JOURNALISTS: Journalist[] = [
  {
    id: 'raphael-honigstein',
    name: 'Raphael Honigstein',
    country: 'germany',
    mediaOutlets: ['the_athletic'],
    primaryLeagues: ['Bundesliga'],
    secondaryLeagues: ['Premier League'],
    clubAffinities: [],
    competitions: ['Bundesliga', 'Champions League'],
    roles: ['columnist', 'reporter'],
    specialties: ['history', 'coaching', 'club_management'],
    eventTypes: ['HISTORIC_RESULT', 'MANAGER_PRESSURE', 'MANAGER_PRAISE', 'BOARD_DECISION', 'TACTICAL_CHANGE', 'MATCH_RESULT'],
    tone: 'sophisticated',
    controversyLevel: 0.2,
    tacticalDepth: 0.5,
    transferReliability: 'OPINION',
    internationalReach: 0.5,
    domesticReach: 0.6,
    clubSpecificity: 0,
    defaultWeight: 0.45,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS'],
  },
  {
    id: 'florian-plettenberg',
    name: 'Florian Plettenberg',
    country: 'germany',
    mediaOutlets: ['sky_deutschland'],
    primaryLeagues: ['Bundesliga'],
    secondaryLeagues: [],
    clubAffinities: [{ clubName: 'Bayern de Munique', level: 'HIGH' }],
    competitions: ['Bundesliga', 'Champions League'],
    roles: ['transfer_reporter', 'reporter'],
    specialties: ['transfers', 'contracts'],
    eventTypes: ['TRANSFER_RUMOR', 'TRANSFER_NEGOTIATION', 'TRANSFER_COMPLETED', 'PLAYER_SALE', 'PLAYER_LOAN', 'CONTRACT_RENEWAL'],
    tone: 'factual',
    controversyLevel: 0.1,
    tacticalDepth: 0.1,
    transferReliability: 'TIER_1',
    internationalReach: 0.45,
    domesticReach: 0.85,
    clubSpecificity: 0.4,
    defaultWeight: 0.55,
    active: true,
    excludedRoleInStory: ['TACTICAL_ANALYSIS', 'POST_MATCH_REACTION'],
  },
  {
    id: 'lothar-matthaus',
    name: 'Lothar Matthäus',
    country: 'germany',
    mediaOutlets: ['sky_deutschland', 'bild'],
    primaryLeagues: ['Bundesliga'],
    secondaryLeagues: [],
    clubAffinities: [{ clubName: 'Bayern de Munique', level: 'HIGH' }],
    competitions: ['Bundesliga', 'Champions League'],
    roles: ['former_player', 'commentator'],
    specialties: ['players', 'coaching', 'club_management'],
    eventTypes: ['MATCH_RESULT', 'MANAGER_PRESSURE', 'MANAGER_PRAISE', 'DERBY', 'CHAMPIONS_LEAGUE_EVENT', 'BOARD_DECISION', 'CLUB_CRISIS'],
    tone: 'critical',
    controversyLevel: 0.7,
    tacticalDepth: 0.45,
    transferReliability: 'OPINION',
    internationalReach: 0.5,
    domesticReach: 0.85,
    clubSpecificity: 0.5,
    defaultWeight: 0.55,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS', 'TRANSFER_UPDATE'],
  },
  {
    id: 'dietmar-hamann',
    name: 'Dietmar Hamann',
    country: 'germany',
    mediaOutlets: ['sky_deutschland'],
    primaryLeagues: ['Bundesliga'],
    secondaryLeagues: ['Premier League'],
    clubAffinities: [],
    competitions: ['Bundesliga', 'Premier League', 'Champions League'],
    roles: ['former_player', 'commentator'],
    specialties: ['players', 'club_management'],
    eventTypes: ['MATCH_RESULT', 'MANAGER_PRESSURE', 'BOARD_DECISION', 'CHAMPIONS_LEAGUE_EVENT', 'LOSING_STREAK'],
    tone: 'critical',
    controversyLevel: 0.6,
    tacticalDepth: 0.45,
    transferReliability: 'OPINION',
    internationalReach: 0.4,
    domesticReach: 0.6,
    clubSpecificity: 0,
    defaultWeight: 0.4,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS', 'TRANSFER_UPDATE'],
  },
  {
    id: 'christoph-kramer',
    name: 'Christoph Kramer',
    country: 'germany',
    mediaOutlets: ['sky_deutschland'],
    primaryLeagues: ['Bundesliga'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Bundesliga', 'Champions League'],
    roles: ['former_player', 'tactical_analyst'],
    specialties: ['tactics', 'players'],
    eventTypes: ['TACTICAL_CHANGE', 'LINEUP_CHANGE', 'PLAYER_FORM', 'MATCH_RESULT'],
    tone: 'technical',
    controversyLevel: 0.2,
    tacticalDepth: 0.75,
    transferReliability: 'OPINION',
    internationalReach: 0.2,
    domesticReach: 0.5,
    clubSpecificity: 0,
    defaultWeight: 0.35,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS', 'TRANSFER_UPDATE'],
  },
]
