import type { Journalist } from '../types'

export const ITALY_JOURNALISTS: Journalist[] = [
  {
    id: 'gianluca-di-marzio',
    name: 'Gianluca Di Marzio',
    country: 'italy',
    mediaOutlets: ['sky_italia'],
    primaryLeagues: ['Serie A'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Serie A', 'Champions League'],
    roles: ['transfer_reporter', 'reporter'],
    specialties: ['transfers', 'contracts'],
    eventTypes: ['TRANSFER_RUMOR', 'TRANSFER_NEGOTIATION', 'TRANSFER_COMPLETED', 'PLAYER_SALE', 'PLAYER_LOAN', 'CONTRACT_RENEWAL'],
    tone: 'factual',
    controversyLevel: 0.1,
    tacticalDepth: 0.1,
    transferReliability: 'TIER_1',
    internationalReach: 0.45,
    domesticReach: 0.9,
    clubSpecificity: 0,
    defaultWeight: 0.65,
    active: true,
    excludedRoleInStory: ['POST_MATCH_REACTION', 'TACTICAL_ANALYSIS'],
  },
  {
    id: 'fabrizio-romano',
    name: 'Fabrizio Romano',
    country: 'italy',
    mediaOutlets: ['the_athletic'],
    primaryLeagues: ['Serie A', 'Premier League', 'La Liga', 'Ligue 1', 'Bundesliga'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Serie A', 'Premier League', 'La Liga', 'Champions League'],
    roles: ['transfer_reporter'],
    specialties: ['transfers', 'contracts'],
    eventTypes: ['TRANSFER_RUMOR', 'TRANSFER_NEGOTIATION', 'TRANSFER_COMPLETED', 'PLAYER_SALE', 'PLAYER_LOAN', 'CONTRACT_RENEWAL'],
    tone: 'factual',
    controversyLevel: 0.1,
    tacticalDepth: 0,
    transferReliability: 'TIER_1',
    internationalReach: 0.95,
    domesticReach: 0.5,
    clubSpecificity: 0,
    // Reservado pra transferências relevantes/internacionais — nunca virar personagem onipresente (§7, doc).
    defaultWeight: 0.55,
    active: true,
    excludedRoleInStory: ['POST_MATCH_REACTION', 'TACTICAL_ANALYSIS', 'CRITICISM', 'PRAISE'],
  },
  {
    id: 'paolo-condo',
    name: 'Paolo Condò',
    country: 'italy',
    mediaOutlets: ['sky_italia'],
    primaryLeagues: ['Serie A'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Serie A', 'Champions League'],
    roles: ['columnist', 'analyst'],
    specialties: ['history', 'coaching', 'domestic_league'],
    eventTypes: ['MATCH_RESULT', 'HISTORIC_RESULT', 'CHAMPIONS_LEAGUE_EVENT', 'MANAGER_PRESSURE', 'MANAGER_PRAISE', 'TITLE_RACE', 'TRANSFER_COMPLETED'],
    tone: 'sophisticated',
    controversyLevel: 0.25,
    tacticalDepth: 0.5,
    transferReliability: 'OPINION',
    internationalReach: 0.35,
    domesticReach: 0.75,
    clubSpecificity: 0,
    defaultWeight: 0.5,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS'],
  },
  {
    id: 'lele-adani',
    name: 'Lele Adani',
    country: 'italy',
    mediaOutlets: ['dazn_italia'],
    primaryLeagues: ['Serie A'],
    secondaryLeagues: ['Champions League'],
    clubAffinities: [],
    competitions: ['Serie A', 'Champions League'],
    roles: ['former_player', 'tactical_analyst'],
    specialties: ['tactics', 'players'],
    eventTypes: ['MATCH_RESULT', 'TACTICAL_CHANGE', 'PLAYER_FORM', 'PLAYER_BREAKOUT', 'CHAMPIONS_LEAGUE_EVENT', 'CUP_FINAL', 'DERBY'],
    tone: 'emotional',
    controversyLevel: 0.5,
    tacticalDepth: 0.85,
    transferReliability: 'OPINION',
    internationalReach: 0.3,
    domesticReach: 0.75,
    clubSpecificity: 0,
    defaultWeight: 0.55,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS', 'TRANSFER_UPDATE'],
  },
  {
    id: 'fabio-caressa',
    name: 'Fabio Caressa',
    country: 'italy',
    mediaOutlets: ['sky_italia'],
    primaryLeagues: ['Serie A'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Serie A', 'Champions League'],
    roles: ['presenter', 'commentator'],
    specialties: ['domestic_league', 'national_team'],
    eventTypes: ['MATCH_RESULT', 'CUP_FINAL', 'DERBY', 'RIVALRY_MATCH', 'WINNING_STREAK', 'LOSING_STREAK', 'TITLE_RACE'],
    tone: 'measured',
    controversyLevel: 0.2,
    tacticalDepth: 0.3,
    transferReliability: 'OPINION',
    internationalReach: 0.15,
    domesticReach: 0.65,
    clubSpecificity: 0,
    defaultWeight: 0.4,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS'],
  },
]
