import type { Journalist } from '../types'

export const PORTUGAL_JOURNALISTS: Journalist[] = [
  {
    id: 'antonio-tadeia',
    name: 'António Tadeia',
    country: 'portugal',
    mediaOutlets: ['a_bola'],
    primaryLeagues: ['Liga Portugal'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Liga Portugal', 'Champions League'],
    roles: ['commentator', 'columnist'],
    specialties: ['domestic_league', 'national_team'],
    eventTypes: ['MATCH_RESULT', 'MANAGER_PRESSURE', 'MANAGER_PRAISE', 'TITLE_RACE', 'DERBY', 'CUP_FINAL'],
    tone: 'measured',
    controversyLevel: 0.3,
    tacticalDepth: 0.4,
    transferReliability: 'OPINION',
    internationalReach: 0.15,
    domesticReach: 0.7,
    clubSpecificity: 0,
    defaultWeight: 0.45,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS'],
  },
  {
    id: 'luis-cristovao',
    name: 'Luís Cristóvão',
    country: 'portugal',
    mediaOutlets: ['record'],
    primaryLeagues: ['Liga Portugal'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Liga Portugal'],
    roles: ['analyst', 'columnist'],
    specialties: ['domestic_league', 'club_management'],
    eventTypes: ['MATCH_RESULT', 'MANAGER_PRESSURE', 'BOARD_DECISION', 'CLUB_CRISIS'],
    tone: 'measured',
    controversyLevel: 0.35,
    tacticalDepth: 0.4,
    transferReliability: 'OPINION',
    internationalReach: 0.1,
    domesticReach: 0.6,
    clubSpecificity: 0,
    defaultWeight: 0.35,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS'],
  },
  {
    id: 'rui-malheiro',
    name: 'Rui Malheiro',
    country: 'portugal',
    mediaOutlets: ['o_jogo'],
    primaryLeagues: ['Liga Portugal'],
    secondaryLeagues: ['Premier League', 'Serie A', 'La Liga'],
    clubAffinities: [],
    competitions: ['Liga Portugal'],
    roles: ['reporter', 'analyst'],
    specialties: ['scouting', 'players', 'international_football'],
    eventTypes: ['TRANSFER_RUMOR', 'TRANSFER_NEGOTIATION', 'PLAYER_BREAKOUT', 'PLAYER_FORM'],
    tone: 'analytical',
    controversyLevel: 0.15,
    tacticalDepth: 0.4,
    transferReliability: 'TIER_2',
    internationalReach: 0.3,
    domesticReach: 0.5,
    clubSpecificity: 0,
    defaultWeight: 0.35,
    active: true,
    excludedRoleInStory: ['POST_MATCH_REACTION'],
  },
  {
    id: 'tomas-da-cunha',
    name: 'Tomás da Cunha',
    country: 'portugal',
    mediaOutlets: ['rtp'],
    primaryLeagues: ['Liga Portugal'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Liga Portugal', 'Champions League'],
    roles: ['tactical_analyst', 'analyst'],
    specialties: ['tactics', 'youth'],
    eventTypes: ['TACTICAL_CHANGE', 'LINEUP_CHANGE', 'PLAYER_BREAKOUT', 'MATCH_RESULT'],
    tone: 'technical',
    controversyLevel: 0.15,
    tacticalDepth: 0.85,
    transferReliability: 'OPINION',
    internationalReach: 0.1,
    domesticReach: 0.45,
    clubSpecificity: 0,
    defaultWeight: 0.3,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS', 'TRANSFER_UPDATE'],
  },
  {
    id: 'pedro-henriques',
    name: 'Pedro Henriques',
    country: 'portugal',
    mediaOutlets: ['record'],
    primaryLeagues: ['Liga Portugal'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Liga Portugal'],
    roles: ['analyst'],
    specialties: ['refereeing'],
    eventTypes: ['REFEREE_CONTROVERSY', 'CONTROVERSY'],
    tone: 'technical',
    controversyLevel: 0.4,
    tacticalDepth: 0.2,
    transferReliability: 'OPINION',
    internationalReach: 0.05,
    domesticReach: 0.4,
    clubSpecificity: 0,
    defaultWeight: 0.3,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS', 'TACTICAL_ANALYSIS', 'TRANSFER_UPDATE'],
  },
]
