import type { Journalist } from '../types'

export const SAUDI_ARABIA_JOURNALISTS: Journalist[] = [
  {
    id: 'walid-al-farraj',
    name: 'Walid Al-Farraj',
    country: 'saudi_arabia',
    mediaOutlets: ['ksa_sports'],
    primaryLeagues: ['Saudi Pro League'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Saudi Pro League'],
    roles: ['commentator', 'columnist'],
    specialties: ['domestic_league', 'club_management'],
    eventTypes: ['MATCH_RESULT', 'MANAGER_PRESSURE', 'BOARD_DECISION', 'TITLE_RACE', 'DERBY'],
    tone: 'measured',
    controversyLevel: 0.25,
    tacticalDepth: 0.3,
    transferReliability: 'OPINION',
    internationalReach: 0.1,
    domesticReach: 0.75,
    clubSpecificity: 0,
    defaultWeight: 0.4,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS'],
  },
  {
    id: 'ahmed-afifi',
    name: 'Ahmed Afifi',
    country: 'saudi_arabia',
    mediaOutlets: ['ksa_sports'],
    primaryLeagues: ['Saudi Pro League'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Saudi Pro League'],
    roles: ['analyst', 'tactical_analyst'],
    specialties: ['tactics', 'players'],
    eventTypes: ['TACTICAL_CHANGE', 'PLAYER_FORM', 'MATCH_RESULT'],
    tone: 'technical',
    controversyLevel: 0.2,
    tacticalDepth: 0.6,
    transferReliability: 'OPINION',
    internationalReach: 0.1,
    domesticReach: 0.55,
    clubSpecificity: 0,
    defaultWeight: 0.3,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS', 'TRANSFER_UPDATE'],
  },
  {
    id: 'turki-al-awad',
    name: 'Turki Al-Awad',
    country: 'saudi_arabia',
    mediaOutlets: ['ksa_sports'],
    primaryLeagues: ['Saudi Pro League'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Saudi Pro League'],
    roles: ['commentator'],
    specialties: ['domestic_league'],
    eventTypes: ['MATCH_RESULT', 'DERBY', 'CUP_FINAL'],
    tone: 'measured',
    controversyLevel: 0.2,
    tacticalDepth: 0.25,
    transferReliability: 'OPINION',
    internationalReach: 0.05,
    domesticReach: 0.5,
    clubSpecificity: 0,
    defaultWeight: 0.25,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS', 'TRANSFER_UPDATE'],
  },
  {
    id: 'abdulrahman-abed',
    name: 'Abdulrahman Abed',
    country: 'saudi_arabia',
    mediaOutlets: ['ksa_sports'],
    primaryLeagues: ['Saudi Pro League'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Saudi Pro League'],
    roles: ['reporter'],
    specialties: ['domestic_league', 'club_management'],
    eventTypes: ['MATCH_RESULT', 'BOARD_DECISION', 'TRANSFER_COMPLETED'],
    tone: 'factual',
    controversyLevel: 0.15,
    tacticalDepth: 0.2,
    transferReliability: 'TIER_3',
    internationalReach: 0.1,
    domesticReach: 0.5,
    clubSpecificity: 0,
    defaultWeight: 0.25,
    active: true,
    excludedRoleInStory: ['TACTICAL_ANALYSIS'],
  },
  {
    id: 'ben-jacobs',
    name: 'Ben Jacobs',
    country: 'saudi_arabia',
    mediaOutlets: ['ksa_sports', 'the_athletic'],
    primaryLeagues: ['Saudi Pro League'],
    secondaryLeagues: ['Premier League'],
    clubAffinities: [],
    competitions: ['Saudi Pro League'],
    roles: ['transfer_reporter', 'reporter'],
    specialties: ['transfers', 'ownership', 'finance'],
    eventTypes: ['TRANSFER_RUMOR', 'TRANSFER_NEGOTIATION', 'TRANSFER_COMPLETED', 'FINANCIAL_DECISION', 'BOARD_DECISION'],
    tone: 'factual',
    controversyLevel: 0.15,
    tacticalDepth: 0.05,
    transferReliability: 'TIER_2',
    internationalReach: 0.55,
    domesticReach: 0.6,
    clubSpecificity: 0,
    defaultWeight: 0.45,
    active: true,
    excludedRoleInStory: ['TACTICAL_ANALYSIS', 'POST_MATCH_REACTION'],
  },
]
