import type { Journalist } from '../types'

export const SPAIN_JOURNALISTS: Journalist[] = [
  {
    id: 'julio-maldonado-maldini',
    name: 'Julio Maldonado "Maldini"',
    country: 'spain',
    mediaOutlets: ['as'],
    primaryLeagues: ['La Liga'],
    secondaryLeagues: ['Premier League', 'Serie A', 'Ligue 1'],
    clubAffinities: [],
    competitions: ['La Liga', 'Champions League'],
    roles: ['reporter', 'analyst'],
    specialties: ['scouting', 'players', 'history', 'international_football'],
    eventTypes: ['TRANSFER_RUMOR', 'TRANSFER_NEGOTIATION', 'PLAYER_BREAKOUT', 'HISTORIC_RESULT'],
    tone: 'sophisticated',
    controversyLevel: 0.2,
    tacticalDepth: 0.4,
    transferReliability: 'TIER_2',
    internationalReach: 0.4,
    domesticReach: 0.6,
    clubSpecificity: 0,
    defaultWeight: 0.4,
    active: true,
    excludedRoleInStory: ['POST_MATCH_REACTION'],
  },
  {
    id: 'miguel-quintana',
    name: 'Miguel Quintana',
    country: 'spain',
    mediaOutlets: ['relevo'],
    primaryLeagues: ['La Liga'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['La Liga', 'Champions League'],
    roles: ['tactical_analyst', 'analyst'],
    specialties: ['tactics', 'players', 'coaching'],
    eventTypes: ['TACTICAL_CHANGE', 'LINEUP_CHANGE', 'PLAYER_FORM', 'MANAGER_PRESSURE', 'MATCH_RESULT'],
    tone: 'technical',
    controversyLevel: 0.25,
    tacticalDepth: 0.85,
    transferReliability: 'OPINION',
    internationalReach: 0.2,
    domesticReach: 0.55,
    clubSpecificity: 0,
    defaultWeight: 0.4,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS', 'TRANSFER_UPDATE'],
  },
  {
    id: 'sid-lowe',
    name: 'Sid Lowe',
    country: 'spain',
    mediaOutlets: ['the_athletic'],
    primaryLeagues: ['La Liga'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['La Liga', 'Champions League'],
    roles: ['columnist', 'reporter'],
    specialties: ['history', 'club_management', 'coaching'],
    eventTypes: ['HISTORIC_RESULT', 'MANAGER_PRESSURE', 'MANAGER_PRAISE', 'CLUB_CRISIS', 'DERBY', 'RIVALRY_MATCH', 'MATCH_RESULT'],
    tone: 'sophisticated',
    controversyLevel: 0.25,
    tacticalDepth: 0.45,
    transferReliability: 'OPINION',
    internationalReach: 0.55,
    domesticReach: 0.55,
    clubSpecificity: 0,
    defaultWeight: 0.45,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS'],
  },
  {
    id: 'guillem-balague',
    name: 'Guillem Balagué',
    country: 'spain',
    mediaOutlets: ['sky_sports'],
    primaryLeagues: ['La Liga'],
    secondaryLeagues: ['Premier League'],
    clubAffinities: [],
    competitions: ['La Liga', 'Premier League', 'Champions League'],
    roles: ['reporter', 'transfer_reporter'],
    specialties: ['transfers', 'club_management', 'coaching', 'locker_room'],
    eventTypes: ['TRANSFER_RUMOR', 'TRANSFER_NEGOTIATION', 'TRANSFER_COMPLETED', 'MANAGER_PRESSURE', 'BOARD_DECISION'],
    tone: 'analytical',
    controversyLevel: 0.25,
    tacticalDepth: 0.3,
    transferReliability: 'TIER_2',
    internationalReach: 0.5,
    domesticReach: 0.55,
    clubSpecificity: 0,
    defaultWeight: 0.4,
    active: true,
    excludedRoleInStory: ['TACTICAL_ANALYSIS'],
  },
  {
    id: 'santi-gimenez',
    name: 'Santi Giménez',
    country: 'spain',
    mediaOutlets: ['mundo_deportivo'],
    primaryLeagues: ['La Liga'],
    secondaryLeagues: [],
    clubAffinities: [{ clubName: 'Barcelona', level: 'HIGH' }],
    competitions: ['La Liga'],
    roles: ['reporter'],
    specialties: ['locker_room', 'club_management'],
    eventTypes: ['MATCH_RESULT', 'BOARD_DECISION', 'MANAGER_PRESSURE', 'TRANSFER_COMPLETED'],
    tone: 'measured',
    controversyLevel: 0.2,
    tacticalDepth: 0.25,
    transferReliability: 'TIER_3',
    internationalReach: 0.15,
    domesticReach: 0.5,
    clubSpecificity: 0.7,
    defaultWeight: 0.3,
    active: true,
    excludedRoleInStory: ['TACTICAL_ANALYSIS'],
  },
]
