import type { Journalist } from '../types'

export const TURKEY_JOURNALISTS: Journalist[] = [
  {
    id: 'mehmet-demirkol',
    name: 'Mehmet Demirkol',
    country: 'turkey',
    mediaOutlets: ['sports_digitale'],
    primaryLeagues: ['Süper Lig'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Süper Lig', 'Champions League'],
    roles: ['columnist', 'analyst'],
    specialties: ['domestic_league', 'coaching'],
    eventTypes: ['MATCH_RESULT', 'MANAGER_PRESSURE', 'MANAGER_PRAISE', 'TITLE_RACE', 'DERBY'],
    tone: 'analytical',
    controversyLevel: 0.3,
    tacticalDepth: 0.4,
    transferReliability: 'OPINION',
    internationalReach: 0.15,
    domesticReach: 0.75,
    clubSpecificity: 0,
    defaultWeight: 0.4,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS'],
  },
  {
    id: 'ugur-meleke',
    name: 'Uğur Meleke',
    country: 'turkey',
    mediaOutlets: ['sports_digitale'],
    primaryLeagues: ['Süper Lig'],
    secondaryLeagues: ['Champions League', 'Premier League', 'La Liga'],
    clubAffinities: [],
    competitions: ['Süper Lig', 'Champions League'],
    roles: ['tactical_analyst', 'analyst'],
    specialties: ['tactics', 'international_football'],
    eventTypes: ['TACTICAL_CHANGE', 'MATCH_RESULT', 'CHAMPIONS_LEAGUE_EVENT', 'EUROPA_EVENT'],
    tone: 'technical',
    controversyLevel: 0.2,
    tacticalDepth: 0.8,
    transferReliability: 'OPINION',
    internationalReach: 0.35,
    domesticReach: 0.55,
    clubSpecificity: 0,
    defaultWeight: 0.4,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS', 'TRANSFER_UPDATE'],
  },
  {
    id: 'ridvan-dilmen',
    name: 'Rıdvan Dilmen',
    country: 'turkey',
    mediaOutlets: ['bein_turkiye'],
    primaryLeagues: ['Süper Lig'],
    secondaryLeagues: [],
    clubAffinities: [{ clubName: 'Fenerbahçe', level: 'HIGH' }],
    competitions: ['Süper Lig'],
    roles: ['former_player', 'commentator'],
    specialties: ['players', 'domestic_league'],
    eventTypes: ['MATCH_RESULT', 'DERBY', 'RIVALRY_MATCH', 'PLAYER_FORM'],
    tone: 'technical',
    controversyLevel: 0.35,
    tacticalDepth: 0.55,
    transferReliability: 'OPINION',
    internationalReach: 0.1,
    domesticReach: 0.65,
    clubSpecificity: 0.5,
    defaultWeight: 0.35,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS', 'TRANSFER_UPDATE'],
  },
  {
    id: 'ugur-karakullukcu',
    name: 'Uğur Karakullukçu',
    country: 'turkey',
    mediaOutlets: ['trt_spor'],
    primaryLeagues: ['Süper Lig'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Süper Lig'],
    roles: ['reporter', 'columnist'],
    specialties: ['domestic_league', 'transfers'],
    eventTypes: ['MATCH_RESULT', 'TRANSFER_RUMOR', 'TRANSFER_COMPLETED'],
    tone: 'analytical',
    controversyLevel: 0.3,
    tacticalDepth: 0.3,
    transferReliability: 'TIER_3',
    internationalReach: 0.1,
    domesticReach: 0.5,
    clubSpecificity: 0,
    defaultWeight: 0.3,
    active: true,
    excludedRoleInStory: ['TACTICAL_ANALYSIS'],
  },
  {
    id: 'serdar-ali-celikler',
    name: 'Serdar Ali Çelikler',
    country: 'turkey',
    mediaOutlets: ['sports_digitale'],
    primaryLeagues: ['Süper Lig'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['Süper Lig'],
    roles: ['columnist'],
    specialties: ['club_management', 'coaching'],
    eventTypes: ['MANAGER_PRESSURE', 'BOARD_DECISION', 'CLUB_CRISIS', 'CONTROVERSY', 'LOSING_STREAK'],
    tone: 'critical',
    controversyLevel: 0.85,
    tacticalDepth: 0.2,
    transferReliability: 'OPINION',
    internationalReach: 0.1,
    domesticReach: 0.6,
    clubSpecificity: 0,
    defaultWeight: 0.35,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS', 'TACTICAL_ANALYSIS'],
  },
]
