import type { Journalist } from '../types'

export const USA_JOURNALISTS: Journalist[] = [
  {
    id: 'tom-bogert',
    name: 'Tom Bogert',
    country: 'usa',
    mediaOutlets: ['mls_media'],
    primaryLeagues: ['MLS'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['MLS'],
    roles: ['transfer_reporter', 'reporter'],
    specialties: ['transfers', 'contracts'],
    eventTypes: ['TRANSFER_RUMOR', 'TRANSFER_NEGOTIATION', 'TRANSFER_COMPLETED', 'PLAYER_SALE', 'PLAYER_LOAN', 'CONTRACT_RENEWAL', 'BOARD_DECISION'],
    tone: 'factual',
    controversyLevel: 0.1,
    tacticalDepth: 0.1,
    transferReliability: 'TIER_1',
    internationalReach: 0.3,
    domesticReach: 0.85,
    clubSpecificity: 0,
    defaultWeight: 0.55,
    active: true,
    excludedRoleInStory: ['TACTICAL_ANALYSIS', 'POST_MATCH_REACTION'],
  },
  {
    id: 'paul-tenorio',
    name: 'Paul Tenorio',
    country: 'usa',
    mediaOutlets: ['the_athletic_us'],
    primaryLeagues: ['MLS'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['MLS'],
    roles: ['reporter', 'analyst'],
    specialties: ['domestic_league', 'club_management', 'national_team'],
    eventTypes: ['MATCH_RESULT', 'BOARD_DECISION', 'MANAGER_PRESSURE', 'TITLE_RACE'],
    tone: 'analytical',
    controversyLevel: 0.2,
    tacticalDepth: 0.35,
    transferReliability: 'OPINION',
    internationalReach: 0.2,
    domesticReach: 0.7,
    clubSpecificity: 0,
    defaultWeight: 0.4,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS'],
  },
  {
    id: 'taylor-twellman',
    name: 'Taylor Twellman',
    country: 'usa',
    mediaOutlets: ['espn_us'],
    primaryLeagues: ['MLS'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['MLS'],
    roles: ['former_player', 'commentator'],
    specialties: ['players', 'national_team'],
    eventTypes: ['MATCH_RESULT', 'PLAYER_FORM', 'PLAYER_BREAKOUT', 'CUP_FINAL'],
    tone: 'critical',
    controversyLevel: 0.45,
    tacticalDepth: 0.4,
    transferReliability: 'OPINION',
    internationalReach: 0.2,
    domesticReach: 0.75,
    clubSpecificity: 0,
    defaultWeight: 0.4,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS', 'TRANSFER_UPDATE'],
  },
  {
    id: 'matt-doyle',
    name: 'Matt Doyle',
    country: 'usa',
    mediaOutlets: ['mls_media'],
    primaryLeagues: ['MLS'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['MLS'],
    roles: ['tactical_analyst', 'analyst'],
    specialties: ['tactics', 'club_management'],
    eventTypes: ['TACTICAL_CHANGE', 'LINEUP_CHANGE', 'MATCH_RESULT', 'BOARD_DECISION'],
    tone: 'technical',
    controversyLevel: 0.2,
    tacticalDepth: 0.75,
    transferReliability: 'OPINION',
    internationalReach: 0.1,
    domesticReach: 0.55,
    clubSpecificity: 0,
    defaultWeight: 0.35,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS', 'TRANSFER_UPDATE'],
  },
  {
    id: 'herculez-gomez',
    name: 'Herculez Gomez',
    country: 'usa',
    mediaOutlets: ['espn_us'],
    primaryLeagues: ['MLS'],
    secondaryLeagues: [],
    clubAffinities: [],
    competitions: ['MLS'],
    roles: ['former_player', 'commentator'],
    specialties: ['national_team', 'players'],
    eventTypes: ['MATCH_RESULT', 'PLAYER_FORM', 'CUP_FINAL'],
    tone: 'measured',
    controversyLevel: 0.3,
    tacticalDepth: 0.35,
    transferReliability: 'OPINION',
    internationalReach: 0.25,
    domesticReach: 0.6,
    clubSpecificity: 0,
    defaultWeight: 0.3,
    active: true,
    excludedRoleInStory: ['BREAKING_NEWS', 'TRANSFER_UPDATE'],
  },
]
